/**
 * Emit `:root { --token-name: value; }` plus the focus-visible utility
 * and the status-pulse keyframes (gated on prefers-reduced-motion).
 */
export function css({ dictionary }) {
  const vars = dictionary.allTokens
    .map((t) => `  --${t.name}: ${cssValue(t)};`)
    .join("\n");

  return `/* Auto-generated by Style Dictionary. Do not edit. */

:root {
${vars}
}

.focus-ring:focus-visible {
  outline: 2px solid var(--color-malina);
  outline-offset: 2px;
}

@media (prefers-reduced-motion: no-preference) {
  @keyframes status-pulse {
    0%, 100% { transform: scale(1); opacity: 1; }
    50% { transform: scale(0.85); opacity: 0.6; }
  }
  .animate-status-pulse {
    animation: status-pulse 2s ease-in-out infinite;
  }
}
`;
}

function cssValue(t) {
  // SD v4 keeps the DTCG $ prefix on all platforms — use $value and $type.
  const type = t.$type;
  const value = t.$value;
  if (type === "shadow" && value && typeof value === "object" && !Array.isArray(value)) {
    const { offsetX, offsetY, blur, spread, color } = value;
    return `${offsetX} ${offsetY} ${blur} ${spread} ${color}`;
  }
  if (type === "strokeStyle" && value && typeof value === "object") {
    return `${value.width} ${value.style} ${value.color}`;
  }
  if (type === "fontFamily" && Array.isArray(value)) {
    return value.map((f) => (f.includes(" ") ? `"${f}"` : f)).join(", ");
  }
  if (type === "cubicBezier" && Array.isArray(value)) {
    return `cubic-bezier(${value.join(", ")})`;
  }
  return String(value);
}
