/**
 * Emit a plain-hex JS object for react-email templates.
 * Only color tokens are exported; typography/size tokens map poorly to
 * inline styles across clients and are better set per-template anyway.
 */
export function email({ dictionary }) {
  const colors = {};
  for (const t of dictionary.allTokens.filter((t) => t.path[0] === "color")) {
    colors[toCamel(t.path[1])] = t.$value;
  }
  const tones = {};
  for (const t of dictionary.allTokens.filter((t) => t.path[0] === "tone")) {
    const name = toCamel(t.path[1]);
    tones[name] ??= {};
    tones[name][t.path[2]] = t.$value;
  }
  return `/* Auto-generated by Style Dictionary. Do not edit. */\nexport const colors = ${JSON.stringify(colors, null, 2)};\nexport const tones = ${JSON.stringify(tones, null, 2)};\n`;
}

function toCamel(s) {
  return s.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
}
