/**
 * Emit a CommonJS Tailwind 3 preset.
 */
export function tailwindCjs({ dictionary }) {
  const preset = buildTailwindPreset(dictionary);
  return `/* Auto-generated by Style Dictionary. Do not edit. */\nmodule.exports = ${JSON.stringify(preset, null, 2)};\n`;
}

export function buildTailwindPreset(dictionary) {
  const get = (path) =>
    dictionary.allTokens.find((t) => t.path.join(".") === path)?.$value;

  const group = (prefix) =>
    Object.fromEntries(
      dictionary.allTokens
        .filter((t) => t.path[0] === prefix)
        .map((t) => [t.path.slice(1).join("-"), t.$value]),
    );

  const colors = group("color");
  Object.assign(colors, group("tone"));

  const fontSize = {};
  for (const t of dictionary.allTokens.filter((t) => t.path.join(".").startsWith("font.size."))) {
    const key = t.path[t.path.length - 1];
    fontSize[key] = [t.$value, { lineHeight: "1.4" }];
  }

  const fontWeight = Object.fromEntries(
    dictionary.allTokens
      .filter((t) => t.path.join(".").startsWith("font.weight."))
      .map((t) => [t.path[t.path.length - 1], String(t.$value)]),
  );

  const spacing = group("spacing");

  const breakpoints = {};
  for (const t of dictionary.allTokens.filter((t) => t.path[0] === "breakpoint")) {
    breakpoints[t.path[1]] = t.$value;
  }

  const contentWidth = {};
  for (const t of dictionary.allTokens.filter((t) => t.path[0] === "content-width")) {
    contentWidth[`content-${t.path[1]}`] = t.$value;
  }

  return {
    theme: {
      extend: {
        colors,
        fontFamily: {
          sans: get("font.family.sans"),
          mono: get("font.family.mono"),
        },
        fontWeight,
        fontSize,
        spacing,
        borderRadius: group("radius"),
        boxShadow: Object.fromEntries(
          dictionary.allTokens
            .filter((t) => t.path[0] === "shadow")
            .map((t) => {
              const { offsetX, offsetY, blur, spread, color } = t.$value;
              return [t.path[1], `${offsetX} ${offsetY} ${blur} ${spread} ${color}`];
            }),
        ),
        screens: breakpoints,
        zIndex: Object.fromEntries(
          dictionary.allTokens
            .filter((t) => t.path[0] === "z-index")
            .map((t) => [t.path[1], String(t.$value)]),
        ),
        opacity: Object.fromEntries(
          dictionary.allTokens
            .filter((t) => t.path[0] === "opacity")
            .map((t) => [t.path[1], String(t.$value)]),
        ),
        transitionDuration: group("duration"),
        transitionTimingFunction: Object.fromEntries(
          dictionary.allTokens
            .filter((t) => t.path[0] === "easing")
            .map((t) => [t.path[1], `cubic-bezier(${t.$value.join(", ")})`]),
        ),
        maxWidth: contentWidth,
      },
    },
  };
}
