import { buildTailwindPreset } from "./tailwind-cjs.mjs";

export function tailwindEsm({ dictionary }) {
  const preset = buildTailwindPreset(dictionary);
  return `/* Auto-generated by Style Dictionary. Do not edit. */\nexport default ${JSON.stringify(preset, null, 2)};\n`;
}
