/**
 * Emit a typed TS module that groups tokens by top-level DTCG category.
 * Output shape:
 *   export const color = { antracit: "#35383d", ... } as const;
 *   export const font = { family: { sans: [...], ... }, ... } as const;
 *   ...
 */
export function typescript({ dictionary }) {
  const groups = {};
  for (const token of dictionary.allTokens) {
    const [root, ...rest] = token.path;
    groups[root] ??= {};
    let cursor = groups[root];
    for (let i = 0; i < rest.length - 1; i++) {
      cursor[rest[i]] ??= {};
      cursor = cursor[rest[i]];
    }
    cursor[rest[rest.length - 1]] = token.$value;
  }

  const serialize = (obj, indent = 2) => {
    const pad = " ".repeat(indent);
    const parentPad = " ".repeat(indent - 2);
    const entries = Object.entries(obj).map(([k, v]) => {
      const key = /^[a-z_$][a-z0-9_$]*$/i.test(k) ? k : JSON.stringify(k);
      if (v && typeof v === "object" && !Array.isArray(v)) {
        return `${pad}${key}: ${serialize(v, indent + 2)}`;
      }
      return `${pad}${key}: ${JSON.stringify(v)}`;
    });
    return `{\n${entries.join(",\n")}\n${parentPad}}`;
  };

  const exports = Object.entries(groups)
    .map(([name, value]) => `export const ${toCamel(name)} = ${serialize(value)} as const;`)
    .join("\n\n");

  return `/* Auto-generated by Style Dictionary. Do not edit. */\n\n${exports}\n`;
}

function toCamel(s) {
  return s.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
}
